<?php

class SubCounter extends Counter
{
    public function increase()
    {
//        parent::increase(); // TODO: Change the autogenerated stub
        $this->count += 2;

    }

    public function decrease()
    {
//        parent::increase(); // TODO: Change the autogenerated stub
        $this->count -= 2;

    }

    public function getResult()
    {
        return $this->count;
    }
}